[theme]
theme = "plain"

[theme.overrides]
idle_bg      = "#0D0800"
idle_fg      = "#FFB000"
info_bg      = "#0D0800"
info_fg      = "#FFC940"
good_bg      = "#0D0800"
good_fg      = "#CC8800"
warning_bg   = "#1A0F00"
warning_fg   = "#FF6600"
critical_bg  = "#FF4400"
critical_fg  = "#0D0800"
separator     = "░"
separator_bg  = "#0D0800"
separator_fg  = "#A67C52"  #"#3D2400"

[icons]
icons = "material-nf"

[[block]]
block = "cpu"
format = " CPU $barchart $utilization "
interval = 5
[[block.click]]
button = "left"
cmd = "alacritty -e htop -s PERCENT_CPU"

[[block]]
block = "memory"
format = " MEM $mem_used "
interval = 5
[[block.click]]
button = "left"
cmd = "alacritty -e htop -s PERCENT_MEM"

[[block]]
block = "disk_space"
path = "/"
[[block.click]]
button = "left"
cmd = "alacritty -e ncdu /"

[[block]]
block = "net"
device = "wlo1"
format = " $icon $ssid $signal_strength "
interval = 5
[[block.click]]
button = "left"
cmd = "alacritty -e nmtui"

[[block]]
block = "net"
format = " ↑ $speed_up.eng(prefix:K) ↓ $speed_down.eng(prefix:K) "
interval = 5

[[block]]
block = "sound"
driver = "pulseaudio"
[[block.click]]
button = "left"
cmd = "alacritty -e pulsemixer"

[[block]]
block = "battery"
format = " BAT $percentage "
interval = 30
[[block.click]]
button = "left"
cmd = "alacritty -e sudo powertop" # Note: requires sudo

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%H:%M:%S') "
interval = 1
[[block.click]]
button = "left"
cmd = "alacritty -e calcurse"
